# 配置应用程序端口号
server:
  port: 8090

# 开启Spring Boot管理端点，并暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 配置Spring应用程序名称，并允许覆盖Bean定义
spring:
  application:
    name: rocketmq-consumer
  main:
    allow-bean-definition-overriding: true  #Spring Boot 2.1 需要设定

  # 配置RocketMQ绑定器，包括NameServer地址和消息绑定的输入通道
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input1:
          destination: test-topic-one  # 消息主题 
          content-type: application/json  # 消息数据格式
          group: test-consumer-group-1  # 消费者组名称
          consumer:
            concurrency: 3 # 消费者线程数; 提高消费能力; Spring Cloud Stream将同时启动3个线程用于名为input1的Binding进行消费
            maxAttempts: 1  # 最多尝试次数; 如果将该属性值定义为1，则表示不允许进行重试
        input2:
          destination: test-topic-two
          content-type: application/json
          group: test-consumer-group-2
